apiVersion: v1
kind: Service
metadata:
  name: fraud-serving
  namespace: fraud-detection
  labels:
    app: fraud-serving
spec:
  # NodePort exposes the service on a port on every node
  # In production this would be LoadBalancer (cloud) or Ingress
  type: NodePort
  selector:
    app: fraud-serving
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30800
